set -eu

export FIREBREAK_WORKER_STATE_DIR=@WORKER_LOCAL_STATE_DIR@
export FIREBREAK_WORKER_AUTHORITY=guest
export FIREBREAK_WORKER_ALLOW_FIREBREAK=0
export FIREBREAK_LIBEXEC_DIR=@WORKER_ENGINE_LIBEXEC_DIR@

exec bash "@WORKER_ENGINE_LIBEXEC_DIR@/firebreak-worker.sh" "$@"
