#!/usr/bin/env bash
set -eu

export FIREBREAK_AGENT_CONFIG_SPECIFIC_VAR='@SPECIFIC_CONFIG_VAR@'
export FIREBREAK_AGENT_CONFIG_SUBDIR='@CONFIG_SUBDIR@'
export FIREBREAK_AGENT_CONFIG_DISPLAY_NAME='@WRAPPER_DISPLAY_NAME@'
export FIREBREAK_AGENT_CONFIG_WORKSPACE_DIR_NAME='@WORKSPACE_DIR_NAME@'

config_dir=$(@RESOLVE_AGENT_CONFIG_BIN@)
export AGENT_CONFIG_DIR="$config_dir"
@CONFIG_ENV_EXPORTS@
exec @REAL_BIN@ "$@"
