if [ "$USER" = "@DEV_USER@" ]; then
  export PS1='[\u@\h:\w]\$ '
  @SHARED_AGENT_CONFIG_ENV_EXPORTS@
  @SHARED_CREDENTIAL_SLOT_ENV_EXPORTS@
  @SHARED_AGENT_WRAPPER_ENV_EXPORTS@

  if [ -n "${FIREBREAK_SHARED_AGENT_WRAPPER_BIN_DIR:-}" ]; then
    export PATH="$FIREBREAK_SHARED_AGENT_WRAPPER_BIN_DIR:$PATH"
  fi

  cdw() {
    target=@WORKSPACE_MOUNT@
    if [ -r @START_DIR_FILE@ ]; then
      target=$(cat @START_DIR_FILE@)
    fi
    cd "$target"
  }

  export FIREBREAK_WORKER_KINDS_FILE=@WORKER_KINDS_FILE@
  export FIREBREAK_WORKER_LOCAL_STATE_DIR=@WORKER_LOCAL_STATE_DIR@
fi
