firebreak_init_usage() {
  cat <<'EOF' >&2
usage:
  firebreak init [--force] [--stdout] [--interactive] [--non-interactive]
EOF
  exit 1
}

firebreak_render_project_config_template() {
  cat <<'EOF'
# Firebreak project defaults
#
# Real environment variables override values in this file.

# Shared config mode for local workload VMs:
AGENT_CONFIG=host

# Public local mode selector:
# FIREBREAK_VM_MODE=run

# Optional shared host config root when AGENT_CONFIG=host.
# Firebreak resolves per-agent subdirectories under this root:
# AGENT_CONFIG_HOST_PATH=~/.firebreak

# Optional per-agent overrides:
# CODEX_CONFIG=workspace
# CLAUDE_CONFIG=workspace
EOF
}

firebreak_render_project_config_from_answers() {
  cat <<'EOF'
# Firebreak project defaults
#
# Generated by 'firebreak init'.
# Real environment variables override values in this file.
EOF
  printf '\n'
  printf 'AGENT_CONFIG=%s\n' "$FIREBREAK_INIT_AGENT_CONFIG"
  printf 'FIREBREAK_VM_MODE=%s\n' "$FIREBREAK_INIT_VM_MODE"

  if [ -n "${FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH:-}" ]; then
    printf 'AGENT_CONFIG_HOST_PATH=%s\n' "$FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH"
  fi

  if [ -n "${FIREBREAK_INIT_CODEX_CONFIG:-}" ] || [ -n "${FIREBREAK_INIT_CLAUDE_CONFIG:-}" ]; then
    printf '\n'
  fi

  if [ -n "${FIREBREAK_INIT_CODEX_CONFIG:-}" ]; then
    printf 'CODEX_CONFIG=%s\n' "$FIREBREAK_INIT_CODEX_CONFIG"
  fi

  if [ -n "${FIREBREAK_INIT_CLAUDE_CONFIG:-}" ]; then
    printf 'CLAUDE_CONFIG=%s\n' "$FIREBREAK_INIT_CLAUDE_CONFIG"
  fi
}

firebreak_init_prompt_choice() {
  prompt=$1
  default_choice=$2
  shift 2

  while :; do
    printf '\n%s\n' "$prompt" >&2
    index=1
    for option in "$@"; do
      label=${option#*|}
      if [ "$index" = "$default_choice" ]; then
        printf '  %s. %s (Default)\n' "$index" "$label" >&2
      else
        printf '  %s. %s\n' "$index" "$label" >&2
      fi
      index=$((index + 1))
    done

    printf 'Choice [%s]: ' "$default_choice" >&2
    if ! IFS= read -r reply; then
      echo "interactive init requires answers on stdin; pass --non-interactive to skip prompts" >&2
      exit 1
    fi
    reply=${reply:-$default_choice}

    index=1
    for option in "$@"; do
      if [ "$reply" = "$index" ]; then
        printf '%s\n' "${option%%|*}"
        return 0
      fi
      index=$((index + 1))
    done

    echo "enter one of the listed numbers" >&2
  done
}

firebreak_init_prompt_yes_no() {
  prompt=$1
  default_answer=$2

  while :; do
    case "$default_answer" in
      y)
        prompt_suffix='[Y/n]'
        ;;
      n)
        prompt_suffix='[y/N]'
        ;;
      *)
        firebreak_init_usage
        ;;
    esac

    printf '%s %s: ' "$prompt" "$prompt_suffix" >&2
    if ! IFS= read -r reply; then
      echo "interactive init requires answers on stdin; pass --non-interactive to skip prompts" >&2
      exit 1
    fi
    reply=$(trim_whitespace "$reply")

    case "$reply" in
      "")
        printf '%s\n' "$default_answer"
        return 0
        ;;
      y|Y|yes|YES)
        printf '%s\n' "y"
        return 0
        ;;
      n|N|no|NO)
        printf '%s\n' "n"
        return 0
        ;;
    esac

    echo "enter y or n" >&2
  done
}

firebreak_init_prompt_path() {
  prompt=$1
  default_value=$2

  while :; do
    printf '%s [%s]: ' "$prompt" "$default_value" >&2
    if ! IFS= read -r reply; then
      echo "interactive init requires answers on stdin; pass --non-interactive to skip prompts" >&2
      exit 1
    fi
    reply=$(trim_whitespace "$reply")
    value=${reply:-$default_value}

    if [ -z "$value" ]; then
      echo "path cannot be empty" >&2
      continue
    fi

    case "$value" in
      *[[:space:]]*)
        echo "paths with whitespace are not supported by the local VM wrapper" >&2
        continue
        ;;
    esac

    printf '%s\n' "$value"
    return 0
  done
}

firebreak_init_collect_agent_override() {
  agent_label=$1
  agent_var_prefix=$2
  add_override=$(firebreak_init_prompt_yes_no "Add a $agent_label-specific override?" "n")
  if [ "$add_override" != "y" ]; then
    return 0
  fi

  selected_mode=$(
    firebreak_init_prompt_choice \
      "Select the default config mode for $agent_label" \
      "3" \
      "workspace|workspace: use the project-local config directory when present" \
      "vm|vm: keep config inside the VM" \
      "host|host: use the shared host config root" \
      "fresh|fresh: start from an empty runtime config each launch"
  )
  printf -v "FIREBREAK_INIT_${agent_var_prefix}_CONFIG" '%s' "$selected_mode"
}

firebreak_init_collect_interactive_answers() {
  FIREBREAK_INIT_AGENT_CONFIG=$(
    firebreak_init_prompt_choice \
      "Select the shared default config mode" \
      "3" \
      "workspace|workspace: use the project-local config directories when present" \
      "vm|vm: keep config inside the VM" \
      "host|host: use a shared host-side config directory" \
      "fresh|fresh: start from an empty runtime config each launch"
  )

  FIREBREAK_INIT_VM_MODE=$(
    firebreak_init_prompt_choice \
      "Select the default local VM mode" \
      "1" \
      "run|run: launch the agent by default" \
      "shell|shell: enter the maintenance shell by default"
  )

  FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH=""
  FIREBREAK_INIT_CODEX_CONFIG=""
  FIREBREAK_INIT_CLAUDE_CONFIG=""

  if [ "$FIREBREAK_INIT_AGENT_CONFIG" = "host" ]; then
    # shellcheck disable=SC2088
    FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH=$(
      firebreak_init_prompt_path \
        "Enter the shared host config path" \
        "~/.firebreak"
    )
  fi

  firebreak_init_collect_agent_override "Codex" "CODEX"
  firebreak_init_collect_agent_override "Claude Code" "CLAUDE"
}

firebreak_init_command() {
  init_force=0
  init_stdout=0
  init_interactive=1

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --force)
        init_force=1
        shift
        ;;
      --stdout)
        init_stdout=1
        shift
        ;;
      --interactive)
        init_interactive=1
        shift
        ;;
      --non-interactive)
        init_interactive=0
        shift
        ;;
      *)
        firebreak_init_usage
        ;;
    esac
  done

  firebreak_reset_project_config_state
  firebreak_resolve_project_config_file
  target_path=$FIREBREAK_RESOLVED_PROJECT_CONFIG_FILE

  if [ "$init_stdout" != "1" ] && [ -e "$target_path" ] && [ "$init_force" != "1" ]; then
    echo "firebreak config file already exists: $target_path" >&2
    echo "use 'firebreak init --force' to overwrite it or 'firebreak doctor' to inspect the resolved state" >&2
    exit 1
  fi

  if [ "$init_interactive" = "1" ]; then
    printf 'Firebreak Init\n' >&2
    printf '\n' >&2
    printf '%s\n' "This will generate a tailored .firebreak.env for the current project." >&2

    firebreak_init_collect_interactive_answers
    rendered_config=$(firebreak_render_project_config_from_answers)

    if [ "$init_stdout" = "1" ]; then
      printf '%s\n' "$rendered_config"
      exit 0
    fi

    printf '\nProposed .firebreak.env\n\n' >&2
    printf '%s\n' "$rendered_config" >&2
    confirm_write=$(firebreak_init_prompt_yes_no "Write this file to $target_path?" "y")
    if [ "$confirm_write" != "y" ]; then
      echo "init aborted before writing .firebreak.env" >&2
      exit 1
    fi

    mkdir -p "$(dirname "$target_path")"
    printf '%s\n' "$rendered_config" >"$target_path"
    echo "wrote Firebreak project defaults: $target_path" >&2
    exit 0
  fi

  if [ "$init_stdout" = "1" ]; then
    firebreak_render_project_config_template
    exit 0
  fi

  mkdir -p "$(dirname "$target_path")"
  firebreak_render_project_config_template >"$target_path"
  echo "wrote Firebreak project defaults: $target_path" >&2
}
