firebreak_init_usage() {
  cat <<'EOF' >&2
usage:
  firebreak init [--force] [--stdout] [--interactive] [--non-interactive]
EOF
  exit 1
}

firebreak_render_project_config_template() {
  cat <<'EOF'
# Firebreak project defaults
#
# Real environment variables override values in this file.

# Shared runtime-state mode for local workload VMs.
# Native project config such as .codex/ or .claude/ still comes from the workspace:
FIREBREAK_STATE_MODE=host

# Public local launch selector:
# FIREBREAK_LAUNCH_MODE=run
# FIREBREAK_WORKER_MODE=local
# FIREBREAK_WORKER_MODES=codex=vm,claude=local

# Optional shared host state root when FIREBREAK_STATE_MODE=host or workspace.
# Firebreak resolves per-tool and per-workspace subdirectories under this root:
# FIREBREAK_STATE_ROOT=~/.firebreak

# Optional per-tool state-mode overrides:
# CODEX_STATE_MODE=workspace
# CLAUDE_STATE_MODE=workspace

# Optional shared credential-slot defaults.
# Slot names are not secrets; they only select which stored credential material to use:
# FIREBREAK_CREDENTIAL_SLOT=default
# FIREBREAK_CREDENTIAL_SLOTS_HOST_PATH=~/.firebreak/credentials
# CODEX_CREDENTIAL_SLOT=backup
# CLAUDE_CREDENTIAL_SLOT=default
EOF
}

firebreak_render_project_config_from_answers() {
  cat <<'EOF'
# Firebreak project defaults
#
# Generated by 'firebreak init'.
# Real environment variables override values in this file.
EOF
  printf '\n'
  printf 'FIREBREAK_STATE_MODE=%s\n' "$FIREBREAK_INIT_STATE_MODE"
  printf 'FIREBREAK_LAUNCH_MODE=%s\n' "$FIREBREAK_INIT_LAUNCH_MODE"

  if [ -n "${FIREBREAK_INIT_STATE_ROOT:-}" ]; then
    printf 'FIREBREAK_STATE_ROOT=%s\n' "$FIREBREAK_INIT_STATE_ROOT"
  fi

  if [ -n "${FIREBREAK_INIT_CODEX_STATE_MODE:-}" ] || [ -n "${FIREBREAK_INIT_CLAUDE_STATE_MODE:-}" ]; then
    printf '\n'
  fi

  if [ -n "${FIREBREAK_INIT_CODEX_STATE_MODE:-}" ]; then
    printf 'CODEX_STATE_MODE=%s\n' "$FIREBREAK_INIT_CODEX_STATE_MODE"
  fi

  if [ -n "${FIREBREAK_INIT_CLAUDE_STATE_MODE:-}" ]; then
    printf 'CLAUDE_STATE_MODE=%s\n' "$FIREBREAK_INIT_CLAUDE_STATE_MODE"
  fi
}

firebreak_init_prompt_choice() {
  prompt=$1
  default_choice=$2
  shift 2

  while :; do
    printf '\n%s\n' "$prompt" >&2
    index=1
    for option in "$@"; do
      label=${option#*|}
      if [ "$index" = "$default_choice" ]; then
        printf '  %s. %s (Default)\n' "$index" "$label" >&2
      else
        printf '  %s. %s\n' "$index" "$label" >&2
      fi
      index=$((index + 1))
    done

    printf 'Choice [%s]: ' "$default_choice" >&2
    if ! IFS= read -r reply; then
      echo "interactive init requires answers on stdin; pass --non-interactive to skip prompts" >&2
      exit 1
    fi
    reply=${reply:-$default_choice}

    index=1
    for option in "$@"; do
      if [ "$reply" = "$index" ]; then
        printf '%s\n' "${option%%|*}"
        return 0
      fi
      index=$((index + 1))
    done

    echo "enter one of the listed numbers" >&2
  done
}

firebreak_init_prompt_yes_no() {
  prompt=$1
  default_answer=$2

  while :; do
    case "$default_answer" in
      y)
        prompt_suffix='[Y/n]'
        ;;
      n)
        prompt_suffix='[y/N]'
        ;;
      *)
        firebreak_init_usage
        ;;
    esac

    printf '%s %s: ' "$prompt" "$prompt_suffix" >&2
    if ! IFS= read -r reply; then
      echo "interactive init requires answers on stdin; pass --non-interactive to skip prompts" >&2
      exit 1
    fi
    reply=$(trim_whitespace "$reply")

    case "$reply" in
      "")
        printf '%s\n' "$default_answer"
        return 0
        ;;
      y|Y|yes|YES)
        printf '%s\n' "y"
        return 0
        ;;
      n|N|no|NO)
        printf '%s\n' "n"
        return 0
        ;;
    esac

    echo "enter y or n" >&2
  done
}

firebreak_init_prompt_path() {
  prompt=$1
  default_value=$2

  while :; do
    printf '%s [%s]: ' "$prompt" "$default_value" >&2
    if ! IFS= read -r reply; then
      echo "interactive init requires answers on stdin; pass --non-interactive to skip prompts" >&2
      exit 1
    fi
    reply=$(trim_whitespace "$reply")
    value=${reply:-$default_value}

    if [ -z "$value" ]; then
      echo "path cannot be empty" >&2
      continue
    fi

    case "$value" in
      *[[:space:]]*)
        echo "paths with whitespace are not supported by the local VM wrapper" >&2
        continue
        ;;
    esac

    printf '%s\n' "$value"
    return 0
  done
}

firebreak_init_collect_tool_override() {
  tool_label=$1
  tool_var_prefix=$2
  add_override=$(firebreak_init_prompt_yes_no "Add a $tool_label-specific override?" "n")
  if [ "$add_override" != "y" ]; then
    return 0
  fi

  selected_mode=$(
    firebreak_init_prompt_choice \
      "Select the default state mode for $tool_label" \
      "3" \
      "workspace|workspace: isolate runtime state per project while keeping native project config from the workspace" \
      "vm|vm: keep runtime state inside the VM" \
      "host|host: use the shared host-side runtime state root" \
      "fresh|fresh: start from empty runtime state each launch"
  )
  printf -v "FIREBREAK_INIT_${tool_var_prefix}_STATE_MODE" '%s' "$selected_mode"
}

firebreak_init_collect_interactive_answers() {
  FIREBREAK_INIT_STATE_MODE=$(
    firebreak_init_prompt_choice \
      "Select the shared default runtime-state mode" \
      "3" \
      "workspace|workspace: isolate runtime state per project while keeping native project config from the workspace" \
      "vm|vm: keep runtime state inside the VM" \
      "host|host: use a shared host-side runtime state root" \
      "fresh|fresh: start from empty runtime state each launch"
  )

  FIREBREAK_INIT_LAUNCH_MODE=$(
    firebreak_init_prompt_choice \
      "Select the default local launch mode" \
      "1" \
      "run|run: launch the agent by default" \
      "shell|shell: enter the maintenance shell by default"
  )

  FIREBREAK_INIT_STATE_ROOT=""
  FIREBREAK_INIT_CODEX_STATE_MODE=""
  FIREBREAK_INIT_CLAUDE_STATE_MODE=""

  if [ "$FIREBREAK_INIT_STATE_MODE" = "host" ]; then
    # shellcheck disable=SC2088
    FIREBREAK_INIT_STATE_ROOT=$(
      firebreak_init_prompt_path \
        "Enter the shared host state root" \
        "~/.firebreak"
    )
  fi

  firebreak_init_collect_tool_override "Codex" "CODEX"
  firebreak_init_collect_tool_override "Claude Code" "CLAUDE"
}

firebreak_init_command() {
  init_force=0
  init_stdout=0
  init_interactive=1

  while [ "$#" -gt 0 ]; do
    case "$1" in
      --force)
        init_force=1
        shift
        ;;
      --stdout)
        init_stdout=1
        shift
        ;;
      --interactive)
        init_interactive=1
        shift
        ;;
      --non-interactive)
        init_interactive=0
        shift
        ;;
      *)
        firebreak_init_usage
        ;;
    esac
  done

  firebreak_reset_project_config_state
  firebreak_resolve_project_config_file
  target_path=$FIREBREAK_RESOLVED_PROJECT_CONFIG_FILE

  if [ "$init_stdout" != "1" ] && [ -e "$target_path" ] && [ "$init_force" != "1" ]; then
    echo "firebreak config file already exists: $target_path" >&2
    echo "use 'firebreak init --force' to overwrite it or 'firebreak doctor' to inspect the resolved state" >&2
    exit 1
  fi

  if [ "$init_interactive" = "1" ]; then
    printf 'Firebreak Init\n' >&2
    printf '\n' >&2
    printf '%s\n' "This will generate a tailored .firebreak.env for the current project." >&2

    firebreak_init_collect_interactive_answers
    rendered_config=$(firebreak_render_project_config_from_answers)

    if [ "$init_stdout" = "1" ]; then
      printf '%s\n' "$rendered_config"
      exit 0
    fi

    printf '\nProposed .firebreak.env\n\n' >&2
    printf '%s\n' "$rendered_config" >&2
    confirm_write=$(firebreak_init_prompt_yes_no "Write this file to $target_path?" "y")
    if [ "$confirm_write" != "y" ]; then
      echo "init aborted before writing .firebreak.env" >&2
      exit 1
    fi

    mkdir -p "$(dirname "$target_path")"
    printf '%s\n' "$rendered_config" >"$target_path"
    echo "wrote Firebreak project defaults: $target_path" >&2
    exit 0
  fi

  if [ "$init_stdout" = "1" ]; then
    firebreak_render_project_config_template
    exit 0
  fi

  mkdir -p "$(dirname "$target_path")"
  firebreak_render_project_config_template >"$target_path"
  echo "wrote Firebreak project defaults: $target_path" >&2
}
