#!/usr/bin/env bash
# Unit tests for firebreak-init.sh render functions and firebreak_init_command.
# Tests source the helper libraries directly and exercise individual functions.
set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PROJECT_CONFIG_LIB="$SCRIPT_DIR/../host/firebreak-project-config.sh"
INIT_LIB="$SCRIPT_DIR/../host/firebreak-init.sh"

if ! [ -f "$PROJECT_CONFIG_LIB" ]; then
  echo "test-unit-init-render: cannot find firebreak-project-config.sh at $PROJECT_CONFIG_LIB" >&2
  exit 1
fi

if ! [ -f "$INIT_LIB" ]; then
  echo "test-unit-init-render: cannot find firebreak-init.sh at $INIT_LIB" >&2
  exit 1
fi

# shellcheck source=../host/firebreak-project-config.sh
. "$PROJECT_CONFIG_LIB"
# shellcheck source=../host/firebreak-init.sh
. "$INIT_LIB"

pass_count=0
fail_count=0

assert_eq() {
  description=$1
  actual=$2
  expected=$3
  if [ "$actual" = "$expected" ]; then
    pass_count=$((pass_count + 1))
  else
    fail_count=$((fail_count + 1))
    echo "FAIL: $description" >&2
    echo "  expected: $(printf '%s' "$expected" | cat -A)" >&2
    echo "  actual:   $(printf '%s' "$actual" | cat -A)" >&2
  fi
}

assert_contains() {
  description=$1
  haystack=$2
  needle=$3
  if printf '%s\n' "$haystack" | grep -F -q -- "$needle"; then
    pass_count=$((pass_count + 1))
  else
    fail_count=$((fail_count + 1))
    echo "FAIL: $description" >&2
    echo "  did not find: $needle" >&2
    echo "  in: $haystack" >&2
  fi
}

assert_not_contains() {
  description=$1
  haystack=$2
  needle=$3
  if ! printf '%s\n' "$haystack" | grep -F -q -- "$needle"; then
    pass_count=$((pass_count + 1))
  else
    fail_count=$((fail_count + 1))
    echo "FAIL: $description" >&2
    echo "  unexpectedly found: $needle" >&2
    echo "  in: $haystack" >&2
  fi
}

tmp_dir=$(mktemp -d)
trap 'rm -rf "$tmp_dir"' EXIT INT TERM

# ---------------------------------------------------------------------------
# firebreak_render_project_config_template
# ---------------------------------------------------------------------------

template=$(firebreak_render_project_config_template)

assert_contains "template contains Firebreak project defaults comment" "$template" "Firebreak project defaults"
assert_contains "template contains AGENT_CONFIG=workspace" "$template" "AGENT_CONFIG=workspace"
assert_contains "template contains FIREBREAK_VM_MODE commented out" "$template" "# FIREBREAK_VM_MODE=run"
assert_contains "template contains AGENT_CONFIG_HOST_PATH commented out" "$template" "# AGENT_CONFIG_HOST_PATH"
assert_contains "template contains CODEX_CONFIG commented out" "$template" "# CODEX_CONFIG=workspace"
assert_contains "template contains CODEX_CONFIG_HOST_PATH commented out" "$template" "# CODEX_CONFIG_HOST_PATH"
assert_contains "template contains CLAUDE_CONFIG commented out" "$template" "# CLAUDE_CONFIG=workspace"
assert_contains "template contains CLAUDE_CONFIG_HOST_PATH commented out" "$template" "# CLAUDE_CONFIG_HOST_PATH"
assert_contains "template has env override note" "$template" "Real environment variables override"

# Template should NOT contain unsupported internal keys
assert_not_contains "template does not contain FIREBREAK_TASK_STATE_DIR" "$template" "FIREBREAK_TASK_STATE_DIR"
assert_not_contains "template does not contain FIREBREAK_TMPDIR" "$template" "FIREBREAK_TMPDIR"
assert_not_contains "template does not contain FIREBREAK_AGENT_MODE" "$template" "FIREBREAK_AGENT_MODE"
assert_not_contains "template does not contain AGENT_VM_ENTRYPOINT" "$template" "AGENT_VM_ENTRYPOINT"

# ---------------------------------------------------------------------------
# firebreak_render_project_config_from_answers - basic workspace/run config
# ---------------------------------------------------------------------------

FIREBREAK_INIT_AGENT_CONFIG="workspace"
FIREBREAK_INIT_VM_MODE="run"
FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CODEX_CONFIG=""
FIREBREAK_INIT_CODEX_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CLAUDE_CONFIG=""
FIREBREAK_INIT_CLAUDE_CONFIG_HOST_PATH=""

rendered=$(firebreak_render_project_config_from_answers)

assert_contains "from_answers renders AGENT_CONFIG=workspace" "$rendered" "AGENT_CONFIG=workspace"
assert_contains "from_answers renders FIREBREAK_VM_MODE=run" "$rendered" "FIREBREAK_VM_MODE=run"
assert_contains "from_answers has generated-by comment" "$rendered" "Generated by 'firebreak init'"
assert_contains "from_answers has env override note" "$rendered" "Real environment variables override"
assert_not_contains "from_answers omits AGENT_CONFIG_HOST_PATH when not set" "$rendered" "AGENT_CONFIG_HOST_PATH"
assert_not_contains "from_answers omits CODEX_CONFIG when not set" "$rendered" "CODEX_CONFIG"
assert_not_contains "from_answers omits CLAUDE_CONFIG when not set" "$rendered" "CLAUDE_CONFIG"

# ---------------------------------------------------------------------------
# firebreak_render_project_config_from_answers - vm/shell config
# ---------------------------------------------------------------------------

FIREBREAK_INIT_AGENT_CONFIG="vm"
FIREBREAK_INIT_VM_MODE="shell"
FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CODEX_CONFIG=""
FIREBREAK_INIT_CODEX_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CLAUDE_CONFIG=""
FIREBREAK_INIT_CLAUDE_CONFIG_HOST_PATH=""

rendered=$(firebreak_render_project_config_from_answers)

assert_contains "from_answers renders AGENT_CONFIG=vm" "$rendered" "AGENT_CONFIG=vm"
assert_contains "from_answers renders FIREBREAK_VM_MODE=shell" "$rendered" "FIREBREAK_VM_MODE=shell"

# ---------------------------------------------------------------------------
# firebreak_render_project_config_from_answers - host mode with path
# ---------------------------------------------------------------------------

FIREBREAK_INIT_AGENT_CONFIG="host"
FIREBREAK_INIT_VM_MODE="run"
FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH="~/.config/firebreak-agent"
FIREBREAK_INIT_CODEX_CONFIG=""
FIREBREAK_INIT_CODEX_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CLAUDE_CONFIG=""
FIREBREAK_INIT_CLAUDE_CONFIG_HOST_PATH=""

rendered=$(firebreak_render_project_config_from_answers)

assert_contains "from_answers renders AGENT_CONFIG=host" "$rendered" "AGENT_CONFIG=host"
assert_contains "from_answers renders AGENT_CONFIG_HOST_PATH" "$rendered" "AGENT_CONFIG_HOST_PATH=~/.config/firebreak-agent"

# ---------------------------------------------------------------------------
# firebreak_render_project_config_from_answers - with agent-specific overrides
# ---------------------------------------------------------------------------

FIREBREAK_INIT_AGENT_CONFIG="workspace"
FIREBREAK_INIT_VM_MODE="run"
FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CODEX_CONFIG="host"
FIREBREAK_INIT_CODEX_CONFIG_HOST_PATH="/custom/codex"
FIREBREAK_INIT_CLAUDE_CONFIG="fresh"
FIREBREAK_INIT_CLAUDE_CONFIG_HOST_PATH=""

rendered=$(firebreak_render_project_config_from_answers)

assert_contains "from_answers renders CODEX_CONFIG=host override" "$rendered" "CODEX_CONFIG=host"
assert_contains "from_answers renders CODEX_CONFIG_HOST_PATH when set" "$rendered" "CODEX_CONFIG_HOST_PATH=/custom/codex"
assert_contains "from_answers renders CLAUDE_CONFIG=fresh override" "$rendered" "CLAUDE_CONFIG=fresh"
assert_not_contains "from_answers omits CLAUDE_CONFIG_HOST_PATH when not set" "$rendered" "CLAUDE_CONFIG_HOST_PATH"

# ---------------------------------------------------------------------------
# firebreak_render_project_config_from_answers - Codex override without host path
# ---------------------------------------------------------------------------

FIREBREAK_INIT_AGENT_CONFIG="workspace"
FIREBREAK_INIT_VM_MODE="run"
FIREBREAK_INIT_AGENT_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CODEX_CONFIG="workspace"
FIREBREAK_INIT_CODEX_CONFIG_HOST_PATH=""
FIREBREAK_INIT_CLAUDE_CONFIG=""
FIREBREAK_INIT_CLAUDE_CONFIG_HOST_PATH=""

rendered=$(firebreak_render_project_config_from_answers)

assert_contains "from_answers renders CODEX_CONFIG=workspace" "$rendered" "CODEX_CONFIG=workspace"
assert_not_contains "from_answers omits CODEX_CONFIG_HOST_PATH when workspace mode" "$rendered" "CODEX_CONFIG_HOST_PATH"

# ---------------------------------------------------------------------------
# firebreak_init_command --non-interactive --stdout
# (tests the full command logic in a subshell, no file writes)
# ---------------------------------------------------------------------------

stdout_output=$(
  cd "$tmp_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  FIREBREAK_RESOLVED_PROJECT_ROOT="$tmp_dir"
  firebreak_init_command --non-interactive --stdout
)

assert_contains "init --non-interactive --stdout outputs template AGENT_CONFIG" "$stdout_output" "AGENT_CONFIG=workspace"
assert_contains "init --non-interactive --stdout outputs commented FIREBREAK_VM_MODE" "$stdout_output" "# FIREBREAK_VM_MODE=run"

# ---------------------------------------------------------------------------
# firebreak_init_command --non-interactive writes file
# ---------------------------------------------------------------------------

project_dir="$tmp_dir/myproject"
mkdir -p "$project_dir"

(
  cd "$project_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  firebreak_init_command --non-interactive >/dev/null 2>&1
)

if ! [ -f "$project_dir/.firebreak.env" ]; then
  fail_count=$((fail_count + 1))
  echo "FAIL: init --non-interactive did not write .firebreak.env" >&2
else
  pass_count=$((pass_count + 1))
  written=$(cat "$project_dir/.firebreak.env")
  assert_contains "init --non-interactive writes AGENT_CONFIG to file" "$written" "AGENT_CONFIG=workspace"
fi

# ---------------------------------------------------------------------------
# firebreak_init_command fails when file exists without --force
# ---------------------------------------------------------------------------

# File already exists from previous test
exit_code=0
(
  cd "$project_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  firebreak_init_command --non-interactive >/dev/null 2>&1
) || exit_code=$?

if [ "$exit_code" -eq 0 ]; then
  fail_count=$((fail_count + 1))
  echo "FAIL: init --non-interactive should fail when .firebreak.env already exists" >&2
else
  pass_count=$((pass_count + 1))
fi

# ---------------------------------------------------------------------------
# firebreak_init_command --force overwrites existing file
# ---------------------------------------------------------------------------

cat >"$project_dir/.firebreak.env" <<'EOF'
AGENT_CONFIG=vm
EOF

(
  cd "$project_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  firebreak_init_command --non-interactive --force >/dev/null 2>&1
)

overwritten=$(cat "$project_dir/.firebreak.env")
assert_contains "init --force overwrites existing file with template" "$overwritten" "AGENT_CONFIG=workspace"

# ---------------------------------------------------------------------------
# firebreak_init_command --stdout skips file write even when file exists
# ---------------------------------------------------------------------------

cat >"$project_dir/.firebreak.env" <<'EOF'
AGENT_CONFIG=vm
EOF

(
  cd "$project_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  firebreak_init_command --non-interactive --stdout >/dev/null 2>&1
)

# File should not have been overwritten
existing=$(cat "$project_dir/.firebreak.env")
assert_contains "init --stdout does not overwrite existing file" "$existing" "AGENT_CONFIG=vm"

# ---------------------------------------------------------------------------
# firebreak_init_command rejects unknown flags
# ---------------------------------------------------------------------------

exit_code=0
(
  cd "$project_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  firebreak_init_command --unknown-flag >/dev/null 2>&1
) || exit_code=$?

if [ "$exit_code" -eq 0 ]; then
  fail_count=$((fail_count + 1))
  echo "FAIL: init should exit nonzero for unknown flags" >&2
else
  pass_count=$((pass_count + 1))
fi

# ---------------------------------------------------------------------------
# firebreak_init_command --interactive fails when stdin is closed
# ---------------------------------------------------------------------------

exit_code=0
(
  cd "$project_dir"
  unset FIREBREAK_PROJECT_CONFIG_FILE 2>/dev/null || true
  firebreak_init_command --interactive --force >/dev/null 2>&1 </dev/null
) || exit_code=$?

if [ "$exit_code" -eq 0 ]; then
  fail_count=$((fail_count + 1))
  echo "FAIL: init --interactive should exit nonzero when stdin is closed" >&2
else
  pass_count=$((pass_count + 1))
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo ""
echo "Results: $pass_count passed, $fail_count failed"

if [ "$fail_count" -gt 0 ]; then
  exit 1
fi

printf '%s\n' "Firebreak init render unit tests passed"